services:
  postgres:
    image: postgres:17

    environment:
      POSTGRES_USER: gmailai
      POSTGRES_PASSWORD: gmailai
      POSTGRES_DB: gmailai

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: